//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportSync.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReportSync.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datasources not loaded.
        /// </summary>
        internal static string DatasourceNotLoaded {
            get {
                return ResourceManager.GetString("DatasourceNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download complete.
        /// </summary>
        internal static string Download_complete {
            get {
                return ResourceManager.GetString("Download_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download failed : .
        /// </summary>
        internal static string Download_failed {
            get {
                return ResourceManager.GetString("Download_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on datasource.
        /// </summary>
        internal static string Error_on_datasource {
            get {
                return ResourceManager.GetString("Error_on_datasource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  failed..
        /// </summary>
        internal static string failed {
            get {
                return ResourceManager.GetString("failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting reports, please wait....
        /// </summary>
        internal static string Getting_reports__please_wait {
            get {
                return ResourceManager.GetString("Getting_reports__please_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect destination user name.
        /// </summary>
        internal static string Incorrect_destination_user_name {
            get {
                return ResourceManager.GetString("Incorrect_destination_user_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect source user name.
        /// </summary>
        internal static string Incorrect_source_user_name {
            get {
                return ResourceManager.GetString("Incorrect_source_user_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading failed..
        /// </summary>
        internal static string Loading_failed {
            get {
                return ResourceManager.GetString("Loading_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please load source and destination directories before you can map datasources..
        /// </summary>
        internal static string MSGBOX_LoadSouceAndDest {
            get {
                return ResourceManager.GetString("MSGBOX_LoadSouceAndDest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please load reports from both source and destination server..
        /// </summary>
        internal static string Please_load_reports_from_both_source_and_destination_server {
            get {
                return ResourceManager.GetString("Please_load_reports_from_both_source_and_destination_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the folder to upload..
        /// </summary>
        internal static string Please_select_the_folder_to_upload {
            get {
                return ResourceManager.GetString("Please_select_the_folder_to_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report files downloaded successfully..
        /// </summary>
        internal static string Report_files_downloaded_successfully {
            get {
                return ResourceManager.GetString("Report_files_downloaded_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync complete.
        /// </summary>
        internal static string Sync_complete {
            get {
                return ResourceManager.GetString("Sync_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync completed successfully..
        /// </summary>
        internal static string Sync_completed_successfully {
            get {
                return ResourceManager.GetString("Sync_completed_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync failed..
        /// </summary>
        internal static string Sync_failed {
            get {
                return ResourceManager.GetString("Sync_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... loading ....
        /// </summary>
        internal static string TreeNodeLoading {
            get {
                return ResourceManager.GetString("TreeNodeLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload .
        /// </summary>
        internal static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload complete.
        /// </summary>
        internal static string Upload_complete {
            get {
                return ResourceManager.GetString("Upload_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload completed successfully..
        /// </summary>
        internal static string Upload_completed_successfully {
            get {
                return ResourceManager.GetString("Upload_completed_successfully", resourceCulture);
            }
        }
    }
}
