//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportSync.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReportSync.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datasources not loaded ähnelt.
        /// </summary>
        internal static string DatasourceNotLoaded {
            get {
                return ResourceManager.GetString("DatasourceNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download complete ähnelt.
        /// </summary>
        internal static string Download_complete {
            get {
                return ResourceManager.GetString("Download_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download failed :  ähnelt.
        /// </summary>
        internal static string Download_failed {
            get {
                return ResourceManager.GetString("Download_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error on datasource ähnelt.
        /// </summary>
        internal static string Error_on_datasource {
            get {
                return ResourceManager.GetString("Error_on_datasource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  failed. ähnelt.
        /// </summary>
        internal static string failed {
            get {
                return ResourceManager.GetString("failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Getting reports, please wait... ähnelt.
        /// </summary>
        internal static string Getting_reports__please_wait {
            get {
                return ResourceManager.GetString("Getting_reports__please_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Incorrect destination user name ähnelt.
        /// </summary>
        internal static string Incorrect_destination_user_name {
            get {
                return ResourceManager.GetString("Incorrect_destination_user_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Incorrect source user name ähnelt.
        /// </summary>
        internal static string Incorrect_source_user_name {
            get {
                return ResourceManager.GetString("Incorrect_source_user_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading failed. ähnelt.
        /// </summary>
        internal static string Loading_failed {
            get {
                return ResourceManager.GetString("Loading_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please load source and destination directories before you can map datasources. ähnelt.
        /// </summary>
        internal static string MSGBOX_LoadSouceAndDest {
            get {
                return ResourceManager.GetString("MSGBOX_LoadSouceAndDest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please load reports from both source and destination server. ähnelt.
        /// </summary>
        internal static string Please_load_reports_from_both_source_and_destination_server {
            get {
                return ResourceManager.GetString("Please_load_reports_from_both_source_and_destination_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select the folder to upload. ähnelt.
        /// </summary>
        internal static string Please_select_the_folder_to_upload {
            get {
                return ResourceManager.GetString("Please_select_the_folder_to_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Report files downloaded successfully. ähnelt.
        /// </summary>
        internal static string Report_files_downloaded_successfully {
            get {
                return ResourceManager.GetString("Report_files_downloaded_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sync complete ähnelt.
        /// </summary>
        internal static string Sync_complete {
            get {
                return ResourceManager.GetString("Sync_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sync completed successfully. ähnelt.
        /// </summary>
        internal static string Sync_completed_successfully {
            get {
                return ResourceManager.GetString("Sync_completed_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sync failed. ähnelt.
        /// </summary>
        internal static string Sync_failed {
            get {
                return ResourceManager.GetString("Sync_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Upload  ähnelt.
        /// </summary>
        internal static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Upload complete ähnelt.
        /// </summary>
        internal static string Upload_complete {
            get {
                return ResourceManager.GetString("Upload_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Upload completed successfully. ähnelt.
        /// </summary>
        internal static string Upload_completed_successfully {
            get {
                return ResourceManager.GetString("Upload_completed_successfully", resourceCulture);
            }
        }
    }
}
